# Site settings
title: devOpsBeta
email: devopsbeta@gmail.com
description: >- # this means to ignore newlines until "baseurl:" 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://devopsbeta.com"
github_username:  devopsbeta

# Build settings
markdown: kramdown
theme: minima
show_excerpts: true
permalink: none
plugins:
  - jekyll-feed
